kind: pipeline
name: lint

workspace:
  base: /go
  path: src/github.com/appleboy/drone-facebook

clone:
  depth: 50

steps:
- name: testing
  image: golang:1.11
  pull: true
  environment:
    GO111MODULE: off
  commands:
  - make vet
  - make lint
  - make test-vendor
  - make misspell-check

trigger:
  event:
  - push

---
kind: pipeline
name: testing

workspace:
  base: /go
  path: src/github.com/appleboy/drone-facebook

clone:
  depth: 50

steps:
- name: testing
  image: golang:1.11
  pull: true
  environment:
    GO111MODULE: off
    FB_PAGE_TOKEN:
      from_secret: fb_page_token
    FB_VERIFY_TOKEN:
      from_secret: fb_verify_token
    FB_TO:
      from_secret: fb_to
  commands:
  - make test
  - make coverage

- name: codecov
  image: robertstettner/drone-codecov
  settings:
    token:
      from_secret: codecov_token

---
kind: pipeline
name: go-module

steps:
- name: testing
  image: golang:1.11
  pull: true
  commands:
  - make build_linux_amd64

trigger:
  event:
  - push

---
kind: pipeline
name: release

clone:
  depth: 50

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: binary
  image: golang:1.11
  pull: true
  commands:
  - make release

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_release_api_key
    files: dist/release/*

trigger:
  event:
  - tag

---
kind: pipeline
name: build_linux_amd64

clone:
  depth: 50

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: binary
  image: golang:1.11
  pull: true
  commands:
  - make build_linux_amd64

- name: publish
  image: plugins/docker:17.12
  settings:
    repo: appleboy/test
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag

depends_on:
- testing

---
kind: pipeline
name: build_linux_i386

clone:
  depth: 50

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: binary
  image: golang:1.11
  pull: true
  commands:
  - make build_linux_i386

- name: publish
  image: plugins/docker:17.12
  settings:
    repo: appleboy/test
    auto_tag: true
    auto_tag_suffix: linux-i386
    dockerfile: Dockerfile.i386
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag

depends_on:
- testing

---
kind: pipeline
name: build_linux_arm

clone:
  depth: 50

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: binary
  image: golang:1.11
  pull: true
  commands:
  - make build_linux_arm

- name: publish
  image: plugins/docker:17.12
  settings:
    repo: appleboy/test
    auto_tag: true
    auto_tag_suffix: linux-arm
    dockerfile: Dockerfile.arm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag

depends_on:
- testing

---
kind: pipeline
name: build_linux_arm64

clone:
  depth: 50

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: binary
  image: golang:1.11
  pull: true
  commands:
  - make build_linux_arm64

- name: publish
  image: plugins/docker:17.12
  settings:
    repo: appleboy/test
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: Dockerfile.arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag

depends_on:
- testing
